### ISSUE TITLE
add translation

### ISSUE THREAD

**Issue by kvdz** [Philip-Scott/Spice-up#101]
There is only english available.  but when you want to have great usability in the appcenter you should show the app with native language support.

**Comment by Philip-Scott** [comment]
All the available strings should be translatable now :) We just need people to actually do the translations

**Comment by kvdz** [comment]
how can someone add the translations?

**Comment by Philip-Scott** [comment]
Since i don't have something like what the rest of the elementary apps use.....

You have to copy the .pot template and rename it to your locale (like how it's named in https://github.com/elementary/scratch/tree/master/po) 

Then just fill in the `""` lines with the translated  text kinda like so: https://github.com/elementary/scratch/blob/master/po/fr.po
