### ISSUE TITLE
Installing on Ubuntu 19.04

### ISSUE THREAD

**Issue by 12people** [Philip-Scott/Spice-up#272]
The PPA does not seem to have a release file for Disco Dingo.

What's the best way to install Spice-up on Ubuntu 19.04?

**Comment by Philip-Scott** [comment]
Hey! So currently Spice-Up does not officially support anything other than the latest Ubuntu LTS release. That said, you might be able to run it by compiling the app from the source code and testing if it works! If that doesn't work, there's also the flatpack version you can use that should work since it uses the LTS libraries :) 

If you can compile it and test if it works, it would be awesome if you could share your results here!

**Comment by 12people** [comment]
Thanks for the Flatpak mention (didn't even think of that) — just installed it!

**Comment by 12people** [comment]
Perhaps you could mention Flathub in the [installation section](https://github.com/Philip-Scott/Spice-up#installation) of your README?
