### ISSUE TITLE
Failed to save work

### ISSUE THREAD

**Issue by Trumpy** [Philip-Scott/Spice-up#277]
## Expected Behavior

To autosave based on changes to the presentation or every x min?

## Current Behavior

Twice I have had the application crash (I think when deleting an image, not sure) while working on a file, losing all the work. No signs that it even existed. 

## Steps to Reproduce (for bugs)

1. Start the program
2. Spend a few hours working on a project
3. Get with-in 10mins of being done with presentation
4. Crash and lose all work.

## Your Environment (for bugs)

Linux elementary-laptop 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
NAME="elementary OS"
VERSION="5.0 Juno"
ID=elementary
ID_LIKE=ubuntu
PRETTY_NAME="elementary OS 5.0 Juno"
LOGO=distributor-logo
VERSION_ID="5.0"
HOME_URL="https://elementary.io/"
SUPPORT_URL="https://elementary.io/support"
BUG_REPORT_URL="https://github.com/elementary/appcenter/issues/new"
PRIVACY_POLICY_URL="https://elementary.io/privacy-policy"
VERSION_CODENAME=juno
UBUNTU_CODENAME=bionic

- Spice-Up Version:  1.8.2 May 5 2019
- OS Info: Elementary Juno

**Comment by Philip-Scott** [comment]
I'm sorry that you had some data loss, that always sucks :( As for auto saving, saving with the current file format is sadly a bit too expensive of an operation because of the way its done. But it's something that will get a lot better with the new file format I was working on over at #266.


As for the crashes, if you can help me to reproduce the issue consistently, that would be amazing! :)

Thank you for reporting the issue!
